# Generated by Django 3.2.15 on 2022-09-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20220901_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='class_no',
            field=models.CharField(default='', max_length=500),
        ),
    ]
